#!/bin/bash
#
# run 
# ./prepare 
# to get the latest version of the this module on the current branch, 
# and the latest committed version of the submodules,
#
# ./prepare --dev 
# does the same, but gets the HEAD of the master branch of each submodule.


git pull

if [ "$1" == "--dev" ]; then
	MODULE_ACTION="git checkout master; git pull";
else
	MODULE_ACTION="git submodule update --init";
	$MODULE_ACTION;
fi

git submodule foreach "$MODULE_ACTION"
